// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbnfeuirphwkfsxdnvuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpibmZldWlycGh3a2ZzeGRudnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzc4NzIsImV4cCI6MjA3NDAxMzg3Mn0.nMfMBymSSVypmCzjuxNTGqoLlI5QTcclHDWkDRYXlrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});